import { z } from 'zod';
import { BusinessRuleViolationError } from '../../../shared/errors/domain-errors';

// Value Objects
export const DeviceCategory = z.enum([
  'IMAGING',
  'MONITORING',
  'EMERGENCY',
  'RESPIRATORY',
  'MOBILITY',
  'SURGICAL',
  'LABORATORY',
  'DIAGNOSTIC'
]);

export const Money = z.object({
  amount: z.number().positive('Amount must be positive'),
  currency: z.string().length(3, 'Currency must be 3 characters'),
});

export const DeviceStock = z.object({
  quantity: z.number().int().min(0, 'Stock cannot be negative'),
  reserved: z.number().int().min(0, 'Reserved quantity cannot be negative'),
});

// Domain Entity
export interface DeviceProps {
  id: string;
  name: string;
  description: string;
  category: z.infer<typeof DeviceCategory>;
  brand: string;
  model: string;
  price: z.infer<typeof Money>;
  rentPrice: z.infer<typeof Money>;
  imageUrl?: string;
  stock: z.infer<typeof DeviceStock>;
  isActive: boolean;
  specifications?: Record<string, unknown>;
  certifications?: string[];
  createdAt: Date;
  updatedAt: Date;
}

export class Device {
  private constructor(private props: DeviceProps) {
    this.validateBusinessRules();
  }

  static create(props: Omit<DeviceProps, 'id' | 'createdAt' | 'updatedAt'>): Device {
    const now = new Date();
    return new Device({
      ...props,
      id: '', // Will be generated by repository
      createdAt: now,
      updatedAt: now,
    });
  }

  static fromPersistence(props: DeviceProps): Device {
    return new Device(props);
  }

  private validateBusinessRules(): void {
    // Business Rule: Rent price should be less than purchase price (daily rate)
    if (this.props.rentPrice.amount >= this.props.price.amount * 0.1) {
      throw new BusinessRuleViolationError(
        'RENT_PRICE_TOO_HIGH',
        'Daily rent price cannot exceed 10% of purchase price'
      );
    }

    // Business Rule: Both prices must be in the same currency
    if (this.props.price.currency !== this.props.rentPrice.currency) {
      throw new BusinessRuleViolationError(
        'CURRENCY_MISMATCH',
        'Purchase and rent prices must be in the same currency'
      );
    }

    // Business Rule: Reserved stock cannot exceed total stock
    if (this.props.stock.reserved > this.props.stock.quantity) {
      throw new BusinessRuleViolationError(
        'INVALID_STOCK_RESERVATION',
        'Reserved stock cannot exceed total stock'
      );
    }
  }

  // Getters
  get id(): string { return this.props.id; }
  get name(): string { return this.props.name; }
  get description(): string { return this.props.description; }
  get category(): z.infer<typeof DeviceCategory> { return this.props.category; }
  get brand(): string { return this.props.brand; }
  get model(): string { return this.props.model; }
  get price(): z.infer<typeof Money> { return { ...this.props.price }; }
  get rentPrice(): z.infer<typeof Money> { return { ...this.props.rentPrice }; }
  get imageUrl(): string | undefined { return this.props.imageUrl; }
  get stock(): z.infer<typeof DeviceStock> { return { ...this.props.stock }; }
  get isActive(): boolean { return this.props.isActive; }
  get specifications(): Record<string, unknown> | undefined { return this.props.specifications; }
  get certifications(): string[] | undefined { return this.props.certifications; }
  get createdAt(): Date { return this.props.createdAt; }
  get updatedAt(): Date { return this.props.updatedAt; }

  // Business Methods
  isAvailableForPurchase(quantity: number = 1): boolean {
    return this.props.isActive && 
           this.availableStock() >= quantity;
  }

  isAvailableForRent(quantity: number = 1): boolean {
    return this.props.isActive && 
           this.availableStock() >= quantity;
  }

  availableStock(): number {
    return this.props.stock.quantity - this.props.stock.reserved;
  }

  reserveStock(quantity: number): void {
    if (!this.isAvailableForPurchase(quantity)) {
      throw new BusinessRuleViolationError(
        'INSUFFICIENT_STOCK',
        `Cannot reserve ${quantity} units. Available: ${this.availableStock()}`
      );
    }

    this.props.stock = {
      ...this.props.stock,
      reserved: this.props.stock.reserved + quantity,
    };
    this.props.updatedAt = new Date();
  }

  releaseStock(quantity: number): void {
    if (this.props.stock.reserved < quantity) {
      throw new BusinessRuleViolationError(
        'INVALID_STOCK_RELEASE',
        `Cannot release ${quantity} units. Reserved: ${this.props.stock.reserved}`
      );
    }

    this.props.stock = {
      ...this.props.stock,
      reserved: this.props.stock.reserved - quantity,
    };
    this.props.updatedAt = new Date();
  }

  adjustStock(newQuantity: number): void {
    if (newQuantity < this.props.stock.reserved) {
      throw new BusinessRuleViolationError(
        'INVALID_STOCK_ADJUSTMENT',
        `Cannot reduce stock below reserved amount (${this.props.stock.reserved})`
      );
    }

    this.props.stock = {
      ...this.props.stock,
      quantity: newQuantity,
    };
    this.props.updatedAt = new Date();
  }

  updatePrice(newPrice: z.infer<typeof Money>): void {
    const validatedPrice = Money.parse(newPrice);
    
    // Validate business rule with new price
    if (this.props.rentPrice.amount >= validatedPrice.amount * 0.1) {
      throw new BusinessRuleViolationError(
        'RENT_PRICE_TOO_HIGH',
        'Current rent price would exceed 10% of new purchase price'
      );
    }

    this.props.price = validatedPrice;
    this.props.updatedAt = new Date();
  }

  updateRentPrice(newRentPrice: z.infer<typeof Money>): void {
    const validatedRentPrice = Money.parse(newRentPrice);
    
    // Validate business rule
    if (validatedRentPrice.amount >= this.props.price.amount * 0.1) {
      throw new BusinessRuleViolationError(
        'RENT_PRICE_TOO_HIGH',
        'Daily rent price cannot exceed 10% of purchase price'
      );
    }

    this.props.rentPrice = validatedRentPrice;
    this.props.updatedAt = new Date();
  }

  activate(): void {
    this.props.isActive = true;
    this.props.updatedAt = new Date();
  }

  deactivate(): void {
    if (this.props.stock.reserved > 0) {
      throw new BusinessRuleViolationError(
        'CANNOT_DEACTIVATE_RESERVED_DEVICE',
        'Cannot deactivate device with reserved stock'
      );
    }

    this.props.isActive = false;
    this.props.updatedAt = new Date();
  }

  // For persistence
  toPersistence(): DeviceProps {
    return { ...this.props };
  }
}

// Device aggregate helpers
export class DeviceFilters {
  constructor(
    public readonly category?: z.infer<typeof DeviceCategory>,
    public readonly brand?: string,
    public readonly priceRange?: { min: number; max: number },
    public readonly availableOnly: boolean = false,
    public readonly searchTerm?: string
  ) {}

  matches(device: Device): boolean {
    if (this.category && device.category !== this.category) return false;
    if (this.brand && device.brand !== this.brand) return false;
    if (this.availableOnly && !device.isAvailableForPurchase()) return false;
    
    if (this.priceRange) {
      const price = device.price.amount;
      if (price < this.priceRange.min || price > this.priceRange.max) return false;
    }

    if (this.searchTerm) {
      const term = this.searchTerm.toLowerCase();
      const searchableText = [
        device.name,
        device.description,
        device.brand,
        device.model,
      ].join(' ').toLowerCase();
      
      if (!searchableText.includes(term)) return false;
    }

    return true;
  }
}
