import { z } from 'zod';
import { BusinessRuleViolationError } from '../../../shared/errors/domain-errors';
import { Money } from './device';

// Value Objects
export const OrderStatus = z.enum([
  'PENDING',
  'CONFIRMED',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
  'REFUNDED'
]);

export const OrderItem = z.object({
  deviceId: z.string(),
  deviceName: z.string(),
  quantity: z.number().int().positive('Quantity must be positive'),
  unitPrice: Money,
  totalPrice: Money,
});

export const ShippingAddress = z.object({
  name: z.string().min(1, 'Name is required'),
  street: z.string().min(1, 'Street is required'),
  city: z.string().min(1, 'City is required'),
  state: z.string().min(1, 'State is required'),
  postalCode: z.string().min(1, 'Postal code is required'),
  country: z.string().min(1, 'Country is required'),
  phone: z.string().optional(),
});

// Domain Entity
export interface OrderProps {
  id: string;
  customerId: string;
  items: z.infer<typeof OrderItem>[];
  status: z.infer<typeof OrderStatus>;
  subtotal: z.infer<typeof Money>;
  taxAmount: z.infer<typeof Money>;
  totalAmount: z.infer<typeof Money>;
  shippingAddress: z.infer<typeof ShippingAddress>;
  paymentId?: string;
  trackingNumber?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
  confirmedAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
  cancelledAt?: Date;
}

export class Order {
  private constructor(private props: OrderProps) {
    this.validateBusinessRules();
  }

  static create(
    customerId: string, 
    items: z.infer<typeof OrderItem>[], 
    shippingAddress: z.infer<typeof ShippingAddress>,
    taxRate: number = 0.15 // 15% VAT in Saudi Arabia
  ): Order {
    if (items.length === 0) {
      throw new BusinessRuleViolationError(
        'EMPTY_ORDER',
        'Order must contain at least one item'
      );
    }

    const now = new Date();
    const subtotal = this.calculateSubtotal(items);
    const taxAmount = this.calculateTax(subtotal, taxRate);
    const totalAmount = this.addAmounts(subtotal, taxAmount);

    return new Order({
      id: '', // Will be generated by repository
      customerId,
      items,
      status: 'PENDING',
      subtotal,
      taxAmount,
      totalAmount,
      shippingAddress: ShippingAddress.parse(shippingAddress),
      createdAt: now,
      updatedAt: now,
    });
  }

  static fromPersistence(props: OrderProps): Order {
    return new Order(props);
  }

  private static calculateSubtotal(items: z.infer<typeof OrderItem>[]): z.infer<typeof Money> {
    const total = items.reduce((sum, item) => sum + item.totalPrice.amount, 0);
    return {
      amount: total,
      currency: items[0].totalPrice.currency,
    };
  }

  private static calculateTax(subtotal: z.infer<typeof Money>, taxRate: number): z.infer<typeof Money> {
    return {
      amount: subtotal.amount * taxRate,
      currency: subtotal.currency,
    };
  }

  private static addAmounts(amount1: z.infer<typeof Money>, amount2: z.infer<typeof Money>): z.infer<typeof Money> {
    if (amount1.currency !== amount2.currency) {
      throw new BusinessRuleViolationError(
        'CURRENCY_MISMATCH',
        'Cannot add amounts with different currencies'
      );
    }

    return {
      amount: amount1.amount + amount2.amount,
      currency: amount1.currency,
    };
  }

  private validateBusinessRules(): void {
    // Business Rule: All items must have the same currency
    const currencies = new Set(this.props.items.map(item => item.totalPrice.currency));
    if (currencies.size > 1) {
      throw new BusinessRuleViolationError(
        'MIXED_CURRENCIES',
        'All order items must use the same currency'
      );
    }

    // Business Rule: Calculated totals must match
    const calculatedSubtotal = Order.calculateSubtotal(this.props.items);
    if (Math.abs(calculatedSubtotal.amount - this.props.subtotal.amount) > 0.01) {
      throw new BusinessRuleViolationError(
        'INVALID_SUBTOTAL',
        'Order subtotal does not match item totals'
      );
    }

    // Business Rule: Total amount must equal subtotal + tax
    const expectedTotal = this.props.subtotal.amount + this.props.taxAmount.amount;
    if (Math.abs(expectedTotal - this.props.totalAmount.amount) > 0.01) {
      throw new BusinessRuleViolationError(
        'INVALID_TOTAL',
        'Order total does not match subtotal + tax'
      );
    }
  }

  // Getters
  get id(): string { return this.props.id; }
  get customerId(): string { return this.props.customerId; }
  get items(): readonly z.infer<typeof OrderItem>[] { return [...this.props.items]; }
  get status(): z.infer<typeof OrderStatus> { return this.props.status; }
  get subtotal(): z.infer<typeof Money> { return { ...this.props.subtotal }; }
  get taxAmount(): z.infer<typeof Money> { return { ...this.props.taxAmount }; }
  get totalAmount(): z.infer<typeof Money> { return { ...this.props.totalAmount }; }
  get shippingAddress(): z.infer<typeof ShippingAddress> { return { ...this.props.shippingAddress }; }
  get paymentId(): string | undefined { return this.props.paymentId; }
  get trackingNumber(): string | undefined { return this.props.trackingNumber; }
  get notes(): string | undefined { return this.props.notes; }
  get createdAt(): Date { return this.props.createdAt; }
  get updatedAt(): Date { return this.props.updatedAt; }
  get confirmedAt(): Date | undefined { return this.props.confirmedAt; }
  get shippedAt(): Date | undefined { return this.props.shippedAt; }
  get deliveredAt(): Date | undefined { return this.props.deliveredAt; }
  get cancelledAt(): Date | undefined { return this.props.cancelledAt; }

  // Status check methods
  isPending(): boolean { return this.props.status === 'PENDING'; }
  isConfirmed(): boolean { return this.props.status === 'CONFIRMED'; }
  isProcessing(): boolean { return this.props.status === 'PROCESSING'; }
  isShipped(): boolean { return this.props.status === 'SHIPPED'; }
  isDelivered(): boolean { return this.props.status === 'DELIVERED'; }
  isCancelled(): boolean { return this.props.status === 'CANCELLED'; }
  isRefunded(): boolean { return this.props.status === 'REFUNDED'; }

  canBeConfirmed(): boolean {
    return this.isPending();
  }

  canBeCancelled(): boolean {
    return this.isPending() || this.isConfirmed();
  }

  canBeShipped(): boolean {
    return this.isConfirmed() || this.isProcessing();
  }

  canBeRefunded(): boolean {
    return this.isDelivered();
  }

  // Business Methods
  confirm(paymentId: string): void {
    if (!this.canBeConfirmed()) {
      throw new BusinessRuleViolationError(
        'INVALID_STATUS_TRANSITION',
        `Cannot confirm order in ${this.props.status} status`
      );
    }

    this.props.status = 'CONFIRMED';
    this.props.paymentId = paymentId;
    this.props.confirmedAt = new Date();
    this.props.updatedAt = new Date();
  }

  startProcessing(): void {
    if (!this.isConfirmed()) {
      throw new BusinessRuleViolationError(
        'INVALID_STATUS_TRANSITION',
        'Can only start processing confirmed orders'
      );
    }

    this.props.status = 'PROCESSING';
    this.props.updatedAt = new Date();
  }

  ship(trackingNumber: string): void {
    if (!this.canBeShipped()) {
      throw new BusinessRuleViolationError(
        'INVALID_STATUS_TRANSITION',
        `Cannot ship order in ${this.props.status} status`
      );
    }

    this.props.status = 'SHIPPED';
    this.props.trackingNumber = trackingNumber;
    this.props.shippedAt = new Date();
    this.props.updatedAt = new Date();
  }

  deliver(): void {
    if (!this.isShipped()) {
      throw new BusinessRuleViolationError(
        'INVALID_STATUS_TRANSITION',
        'Can only deliver shipped orders'
      );
    }

    this.props.status = 'DELIVERED';
    this.props.deliveredAt = new Date();
    this.props.updatedAt = new Date();
  }

  cancel(reason?: string): void {
    if (!this.canBeCancelled()) {
      throw new BusinessRuleViolationError(
        'INVALID_STATUS_TRANSITION',
        `Cannot cancel order in ${this.props.status} status`
      );
    }

    this.props.status = 'CANCELLED';
    this.props.cancelledAt = new Date();
    this.props.updatedAt = new Date();
    
    if (reason) {
      this.props.notes = this.props.notes 
        ? `${this.props.notes}\nCancellation reason: ${reason}`
        : `Cancellation reason: ${reason}`;
    }
  }

  refund(): void {
    if (!this.canBeRefunded()) {
      throw new BusinessRuleViolationError(
        'INVALID_STATUS_TRANSITION',
        'Can only refund delivered orders'
      );
    }

    this.props.status = 'REFUNDED';
    this.props.updatedAt = new Date();
  }

  addNotes(notes: string): void {
    this.props.notes = this.props.notes 
      ? `${this.props.notes}\n${notes}`
      : notes;
    this.props.updatedAt = new Date();
  }

  updateShippingAddress(address: z.infer<typeof ShippingAddress>): void {
    if (!this.isPending() && !this.isConfirmed()) {
      throw new BusinessRuleViolationError(
        'CANNOT_UPDATE_SHIPPING',
        'Cannot update shipping address for orders that are being processed'
      );
    }

    this.props.shippingAddress = ShippingAddress.parse(address);
    this.props.updatedAt = new Date();
  }

  // Calculate business metrics
  getItemCount(): number {
    return this.props.items.reduce((total, item) => total + item.quantity, 0);
  }

  getUniqueDeviceCount(): number {
    return new Set(this.props.items.map(item => item.deviceId)).size;
  }

  // For persistence
  toPersistence(): OrderProps {
    return { ...this.props };
  }
}
